
[Factions]
  Balance = 0
  DTR = 1.1
  Points = 0

[Provider]
  Address = "cluster0.y05ycq4.mongodb.net"
  Dbname = "test"
  Password = "xavier123"
  ProviderName = "MongoDB"
  Username = "xavier"

[Server]
  Whitelisted = true
